config/routes.rb
Rails.application.routes.draw do
  # routes for users authentication
  devise_for :users
  # route for root site
  root 'home#index'
  # routes for groups requests
  resources :groups
  post '/upgrade', to: 'stripe#upgrade'
  post '/downgrade', to: 'stripe#downgrade'
  post '/billing/create', to: 'preferences#billing', as: 'billing_portal_create'
  get '/account/suscription', to: 'preferences#plan'
  resources :webhooks, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: groups
#
#  id          :bigint           not null, primary key
#  amount      :decimal(, )
#  description :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint           not null
#  owner_id    :bigint           not null
#
# Indexes
#
#  index_groups_on_category_id  (category_id)
#  index_groups_on_owner_id     (owner_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (owner_id => users.id)
#
class Group < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  has_many :participating_users, class_name: 'Participant'
  has_many :participants, through: :participating_users, source: :user, dependent: :destroy
  belongs_to :category
  validates :participating_users, presence: true
  validates :name, :description, presence: true
  validates_numericality_of :amount
  accepts_nested_attributes_for :participating_users, allow_destroy: true

  def self.owned_and_participating(current_user_id)
    joins(:participants)
      .where(
        [
          'owner_id = :current_user_id OR participants.user_id = :current_user_id',
          { current_user_id: current_user_id }
        ]
      ).group(:id)
  end

  def self.participating(current_user_id)
    joins(:participants)
      .where(
        [
          'participants.user_id = :current_user_id',
          { current_user_id: current_user_id }
        ]
      ).group(:id).order(created_at: :desc)
  end

  def self.owned(current_user_id)
    joins(:participants)
      .where(
        [
          'owner_id = :current_user_id',
          { current_user_id: current_user_id }
        ]
      ).group(:id).order(created_at: :desc)
  end

  def self.owned_restrict_groups(current_user)
    current_user.premium? ? owned(current_user.id) : owned(current_user.id).limit(4)
  end

  def quantity_of_people_in_group
    participating_users.size + 1
  end

  def individual_contribution
    (amount / quantity_of_people_in_group)
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

# Class to manage the group requests and giving actions for render its views
class GroupsController < ApplicationController
  load_and_authorize_resource
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!
  layout 'dashboard'
  def index
    @groups_owned = Group.owned_restrict_groups(current_user)
    @groups = Group.participating(current_user.id)
  end

  def new
    if current_user.can_create_groups?
      @group = Group.new
    else
      redirect_to groups_path, notice: 'You need upgrade your account to create more groups'
    end
  end

  def create
    @group = Group.new(group_params)
    @group.owner = current_user
    if @group.save
      redirect_to @group, notice: 'Group was successfully created'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @group.update(group_params)
      redirect_to @group
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path, notice: 'El grupo ha sido eliminado exitosamente'
  end

  private

  def set_group
    @group = Group.find params[:id]
  end

  def group_params
    params.require(:group).permit(
      :name,
      :description,
      :amount,
      :owner_id,
      :category_id,
      participating_users_attributes: Participant.attribute_names.map(&:to_sym).push(:_destroy)
    )
  end
end

app/views/groups/_form.html.erb
<%= simple_form_for @group do |f| %>
	<% if @group.errors.any? %>
		<div id="error_explanation" class="container">
			<div class="col-12 col-md-6 offset-md-3 mt-3">
				<h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
				<ul>
					<% @group.errors.each do |error| %>
						<li><%= error.full_message %></li>
					<% end %>
				</ul>
				
			</div>
		</div>
	<% end %>

	<div class="form-group col-12 col-md-6 offset-md-3 my-2">
		<hr>
		<%= f.input :name, :input_html => { :class => 'form-control my-2' } %>
		<%= f.input :description, as: :text, :input_html => { :class => 'form-control my-2' } %>
		<%= f.input :amount, :input_html => { :class => 'form-control my-2' } %>
		<%= f.association :category , :input_html => { :class => 'form-control my-2' } %>
		<div id="addParticipants" class="my-3 d-flex justify-content-end" >
			<%= link_to_add_association f, :participating_users, class:'btn btn-outline-dark' do  %>
				Add Participant
			<% end %>
		</div>
		<div class="participants mt-3">
			<%= f.simple_fields_for :participating_users do |g| %>
				<%= render  'participating_user_fields', f:g %>
			<% end %>
			<div class="participants-container"></div>
		</div>
	</div>
	<div class="col-12 col-md-6 offset-md-3 border-top border-gray mt-3 pt-3">
		<%= f.button :submit , class:'btn btn-dark col-12 mb-3 py-3'  %>
	</div>
<%end%>

app/views/groups/_group.html.erb
<div class="card mb-3 col-12 col-md-4 border-0 text-dark nav-link">
	<%= image_tag "https://dummyimage.com/600x400/000000/9e9e9e&text=#{group.name.parameterize(separator:'+')}", alt: 'src', class:'card-img-top' %>
	<div class="card-body">
		<%= link_to group, class:'text-dark nav-link text-center text-uppercase border-bottom border-dark mb-2' do %>
			<h5 class="card-title my-0"><%= group.name %></h5>
		<% end %>
		<p class="card-text"><strong>Amount:</strong> <%= number_to_currency(group.amount) %></p>
		<p class="card-text"><strong>My Contribution:</strong> <%= number_to_currency(group.individual_contribution) %></p>
	</div>
	<div class="card-footer border border-dark text-dark d-flex justify-content-center align-items-center">
		<div class="d-flex flex-column mx-2 justify-content-start">
			<small class="text-muted">Created <%= time_ago_in_words(group.created_at)  %></small>
			<div class="border-bottom border-white p-2">
				Participants <%= group.participants.size %>
			</div>
		</div>
		<div class="d-flex flex-column mx-2">
			<%= link_to 'Edit', edit_group_path(group), class:'btn btn-info my-1' %>
			<%= link_to 'Delete', group, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger my-1'  %>
		</div>
	</div>
</div>

app/views/groups/_participating_user_fields.erb
<div class="nested-fields container">
	<div class="row mb-2 flex align-items-center">
		<div class="col-9">
			<%= f.input :user_id, as: :select, collection: User.all - [current_user],  label_method: -> (u) { u.email }, :input_html => { :class => 'form-control' }  %>
		</div>
		<div class="col-3">
			<%= link_to_remove_association f, class: 'btn btn-outline-dark btn-sm btn-flat col-12' do  %>
				x
			<% end %>
		</div>
	</div>
</div>

app/views/groups/edit.html.erb
<div class="col-6 offset-3">
	<h1>Edit Group</h1>
	<%= link_to 'Back', groups_path, class:'btn btn-outline-info' %>
	<%= link_to 'Show', @group , class:'btn btn-outline-info '%>
</div>
<%= render 'form', group: @group %>

app/views/groups/index.html.erb
<div class="container">
	<div class="row my-3">
		<h2>Groups Contribution: <%= number_to_currency(current_user.groups_contribution) %> </h2>
	</div>
	<hr>
	<div class="row">
			<h3>My Groups</h3>
	</div>
	<div class="row">
		<%= render @groups_owned %>
	</div>
	<div class="row">
		<h3>Groups where i am</h3>
	</div>
	<div class="row">
		<%= render @groups %>
	</div>
	<div class="row">
		<div class="d-flex my-5 justify-content-center flex-column col-12 col-md-6 offset-md-3">
			<%=create_group_button(current_user) %>
		</div>
	</div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <h1 class="text-center mt-4">New Group</h1>
  <%= render "form"%>
</div>

app/views/groups/show.html.erb
<div class="container">
	<div class="row mt-4">
		<div class="col-12 col-md-6 offset-md-3">
			<%= image_tag "https://dummyimage.com/600x400/000000/9e9e9e&text=#{@group.name.parameterize(separator:'+')}", alt: 'src', class:'img-fluid' %>
		</div>
	</div>
	<div class="row">
		<div class="col-12 col-md-6 offset-md-3">
			<p id="notice"><%= notice %></p>
			<p>
				<strong>Administrator:</strong>
				<%= @group.owner.email %>
			</p>
			<p>
				<strong>Group Name:</strong>
				<%= @group.name %>
			</p>
			<p>
				<strong>Group Description:</strong>
				<%= @group.description %>
			</p>
			<p>
				<strong>Group Amount:</strong>
				<%=number_to_currency(@group.amount,locale: :en) %>
			</p>
			<div class="my-3">
				<strong>Participants:</strong>
				<%@group.participants.each do |participant| %>
					<div class="d-flex flex-wrap">
						<span> <strong>Email:</strong> <%=participant.email%></span>
						<span class="mx-0 mx-md-2"> <strong>Contribution:</strong> <%=number_to_currency(@group.individual_contribution)%></span>
					</div>
				<% end %>
			</div>
			<div class="col-12 d-flex border-top border-gray mt-3 pt-3 mb-5 justify-content-between">
				<%= link_to 'Edit', edit_group_path(@group), class:'btn btn-outline-dark col-5' %>
				<%= link_to 'Back', groups_path , class:'btn btn-outline-dark col-5'%>
			</div>
		</div>
	</div>
</div>