config/routes.rb
Rails.application.routes.draw do
  # routes for users authentication
  devise_for :users
  # route for root site
  root 'home#index'
  # routes for groups requests
  resources :groups
  post '/upgrade', to: 'stripe#upgrade'
  post '/downgrade', to: 'stripe#downgrade'
  post '/billing/create', to: 'preferences#billing', as: 'billing_portal_create'
  get '/account/suscription', to: 'preferences#plan'
  resources :webhooks, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/preferences_controller.rb
# frozen_string_literal: true

# Class to manage manage the billing portal and to show current user actual plan
class PreferencesController < ApplicationController
  layout 'dashboard'
  def plan; end

  def billing
    current_user.create_stripe_id if current_user.stripe_id.nil?
    customer = Stripe::Customer.retrieve(current_user.stripe_id)
    session = Stripe::BillingPortal::Session.create({
                                                      customer: customer,
                                                      return_url: account_suscription_url
                                                    })
    redirect_to session.url
  end
end

app/views/preferences/plan.html.erb
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h3>My Suscription Plan</h3>
		</div>
	</div>
	<div class="row">
		<div class="col-6 offset-3">
			<div class="card">
				<div class="card-body text-center">
					<h5 class="card-title"><%= current_user.role.upcase  %></h5>
					<p class="card-text"><%= render_plan_description(current_user) %></p>
					<% if current_user.premium? %>
						<%= link_to downgrade_path, class: 'btn btn-outline-dark', method: :post do %>
							Change my Plan to free
						<% end %>
					<% else %>
						<%= link_to upgrade_path, class: 'btn btn-dark' , method: :post, remote: true do %>
							Upgrade Plan to Premium
						<% end %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>