config/routes.rb
Rails.application.routes.draw do
  # routes for users authentication
  devise_for :users
  # route for root site
  root 'home#index'
  # routes for groups requests
  resources :groups
  post '/upgrade', to: 'stripe#upgrade'
  post '/downgrade', to: 'stripe#downgrade'
  post '/billing/create', to: 'preferences#billing', as: 'billing_portal_create'
  get '/account/suscription', to: 'preferences#plan'
  resources :webhooks, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/partials/_footer.html.erb
<section class='footer'>
  <div class='footer__container'>
    <div class='footer__social-container'>
      <%= render_svg 'twitter', styles: 'footer__social' %>
      <%= render_svg 'instagram', styles: 'footer__social' %>
      <%= render_svg 'facebook', styles: 'footer__social' %>
    </div>
    <div class='footer__logo-container'>
      <%= render_svg 'logo-mobile', styles: 'footer__logo-mobile' %>
      <%= render_svg 'logo-header', styles: 'footer__logo-desktop' %>
    </div>
  </div>
</section>

app/views/layouts/partials/_messages.html.erb
<% flash.each do |name, msg| %>
	<% if msg.is_a?(String) %>
		<div data-controller="alert" data-alert-animation-class="fade" data-alert-auto-close="5000" role="alert" class="fixed-top d-flex justify-content-center align-items-center alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
			<%= content_tag :div, msg, :id => "flash_#{name}" %>
			<button aria-hidden="true" class="close btn btn-outline-dark mx-2 rounded-circle" data-dismiss="alert" type="button" data-action="click->alert#close">&times;</button>
		</div>
	<% end %>
<% end %>

app/views/layouts/partials/_nav.html.erb
<% if signed_in? %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Register", new_user_registration_path %>
  <%= link_to "Login", new_user_session_path %>
<% end %>

app/views/layouts/partials/_nav_private.html.erb
<nav class="nav-bar">
	<div class="nav-bar__container">
		<div>
			<%= link_to root_path, class: 'link' do %>
				<%= render_svg 'logo-header', styles: 'nav-bar__logo' %>
			<% end %>
		</div>
	
		<div class="buttons-container d-flex align-items-center">
			<% unless !current_user %>
				<ul class="section-container">
					<li class="section-container__link">
						<%= link_to "Groups", groups_path %>
					</li>
				</ul>
				<%= render 'layouts/partials/user_account' %>
			<% end %>
		</div>
	</div>
</nav>

app/views/layouts/partials/_nav_public.html.erb
<section class="nav-bar">
  <div class="nav-bar__container">
    <div>
      <%= render_svg 'logo-header', styles: 'nav-bar__logo' %>
    </div>

    <ul class="section-container">
      <li class="section-container__link">
        <%= link_to "PRODUCTS", "#products" %>
      </li>
      <li class="section-container__link">
        <%= link_to "PRICING", "#pricing" %>
      </li>
      <li class="section-container__link">
        <%= link_to "ABOUT US", "#about-us" %>
      </li>
    </ul>

    <div class="buttons-container">
      <%= render 'layouts/partials/user_options', style_nav: true %>
    </div>

  </div>
</section>

app/views/layouts/partials/_user_account.html.erb
<div class="dropdown">
	<%= link_to '#', class: 'dropdown-toggle btn btn-lg border-dark', data:{ "bs-toggle" => "dropdown"} do %>
		<%= render_svg 'user'%> Account
	<% end %>
	<div class="dropdown-menu">
		<%= link_to groups_path, class: 'dropdown-item groups-navbar' do %>
			Groups
		<% end %>
		<%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
			Edit Account
		<% end %>
		<%= link_to account_suscription_path, class: 'dropdown-item' do %>
			My Suscription
		<% end %>
		<%= link_to billing_portal_create_path, class: 'dropdown-item', method: :post do %>
			Billing
		<% end %>
		<%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item exit" %>
	</div>
</div>

app/views/layouts/partials/_user_options.html.erb
<% if signed_in? %>
  <div class="d-flex align-items-center">
    <ul class="section-container">
      <li class="section-container__link">
        <%= link_to "Groups", groups_path %>
      </li>
    </ul>
    <%= render 'layouts/partials/user_account' %>
  </div>
<% else %>
  <%= link_to "Login", new_user_session_path, class: "btn-login #{class_private(style_nav)}" %>
  <%= link_to "Register", new_user_registration_path, class: "btn-register #{class_private(style_nav)}" %>
<% end %>